/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FounderMessagesRouteImport } from './routes/founder-messages'
import { Route as FounderAnalyticsRouteImport } from './routes/founder-analytics'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as IndexRouteImport } from './routes/index'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderMessagesRoute = FounderMessagesRouteImport.update({
  id: '/founder-messages',
  path: '/founder-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderAnalyticsRoute = FounderAnalyticsRouteImport.update({
  id: '/founder-analytics',
  path: '/founder-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/founder': typeof FounderRoute
  '/founder-analytics': typeof FounderAnalyticsRoute
  '/founder-messages': typeof FounderMessagesRoute
  '/inbox': typeof InboxRoute
  '/network': typeof NetworkRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/founder': typeof FounderRoute
  '/founder-analytics': typeof FounderAnalyticsRoute
  '/founder-messages': typeof FounderMessagesRoute
  '/inbox': typeof InboxRoute
  '/network': typeof NetworkRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/founder': typeof FounderRoute
  '/founder-analytics': typeof FounderAnalyticsRoute
  '/founder-messages': typeof FounderMessagesRoute
  '/inbox': typeof InboxRoute
  '/network': typeof NetworkRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/founder'
    | '/founder-analytics'
    | '/founder-messages'
    | '/inbox'
    | '/network'
    | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/founder'
    | '/founder-analytics'
    | '/founder-messages'
    | '/inbox'
    | '/network'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/founder'
    | '/founder-analytics'
    | '/founder-messages'
    | '/inbox'
    | '/network'
    | '/portfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FounderRoute: typeof FounderRoute
  FounderAnalyticsRoute: typeof FounderAnalyticsRoute
  FounderMessagesRoute: typeof FounderMessagesRoute
  InboxRoute: typeof InboxRoute
  NetworkRoute: typeof NetworkRoute
  PortfolioRoute: typeof PortfolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-messages': {
      id: '/founder-messages'
      path: '/founder-messages'
      fullPath: '/founder-messages'
      preLoaderRoute: typeof FounderMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-analytics': {
      id: '/founder-analytics'
      path: '/founder-analytics'
      fullPath: '/founder-analytics'
      preLoaderRoute: typeof FounderAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FounderRoute: FounderRoute,
  FounderAnalyticsRoute: FounderAnalyticsRoute,
  FounderMessagesRoute: FounderMessagesRoute,
  InboxRoute: InboxRoute,
  NetworkRoute: NetworkRoute,
  PortfolioRoute: PortfolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
